<?php

/**
 * @file
 * Contains mymodule.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mymodule_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mymodule module.
    case 'help.page.mymodule':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Demonstrate a custom compound field plugin, with widget and formatter, extending the base Image module..') . '</p>';
      return $output;

    default:
  }
}
